.SILENT:

PROGRAMS = Test1 Test2 Test3 Test3Bis

GPP = g++ -m64 -Wall -lpthread

all: $(PROGRAMS)

Test1: Exercice1.c
	echo Creation de Test1
	$(GPP) -o Test1  Exercice1.c

Test2: Exercice2.c
	echo Creation de Test2
	$(GPP) -o Test2  Exercice2.c

Test3: Exercice3.c
	echo Creation de Test3
	$(GPP) -o Test3  Exercice3.c
	
Test3Bis: Exercice3Bis.c
	echo Creation de Test3Bis
	$(GPP) -o Test3Bis  Exercice3Bis.c
